name: Jira Issue Updater
description: Updates various properties of a Jira issue
author: frieder
branding:
  icon: edit
  color: black
inputs:
  retries:
    description: The number of retries to connect to the Jira API before considered failed.
    required: false
    default: 1
  retryDelay:
    description: The time in seconds to wait in between connection attempts.
    required: false
    default: 10
  timeout:
    description: The time in milliseconds in which a request must finish or otherwise considered failed.
    required: false
    default: 2000
  failOnError:
    description: Should the action report back as failed when at least one issue cannot be updated.
    type: boolean
    required: false
    default: true
  issue:
    description: The ID(s) of the Jira issue(s).
    required: true
  summary:
    description: The title (summary) of the Jira ticket.
    required: false
  description:
    description: The description of the Jira ticket.
    required: false
  assignee:
    description: The user assigned to the ticket.
    required: false
  priority:
    description: Define the priority of a ticket.
    required: false
  duedate:
    description: Define the due date of a ticket.
    required: false
  resolution:
    description: Define the resolution of the ticket.
    required: false
  components:
    description: Define components to be added/removed/set to the ticket.
    required: false
  fixversions:
    description: A list of fix versions to be added/removed/set to the ticket.
    required: false
  labels:
    description: A list of labels to be added/removed/set to the ticket.
    required: false
  customfields:
    description: A list of custom fields with their respective values.
    required: false
  customfieldsJson:
    description: A list of custom fields with their respective values in JSON. Supports Atlassian Documents and multiple values.
    required: false
runs:
  using: node16
  main: ./dist/index.js
